build_name = eps 

link_script = config/linker_stm32l152VBx.ld

mach_flags = -mthumb -mfloat-abi=softfp -mfpu=fpv4-sp-d16 -fsingle-precision-constant -finline-functions -Wdouble-promotion 

defines += BOARD_EPS

include Makefile.freertos
include Makefile.stm32l1
