### Project-specific makefile

# project_name = program
# sources =
# language = c++

# cross_compile =
# w_flags =
# c_flags =
# cflags +=
# cxxflags +=

# language =

# defines +=
# include_dirs +=
# includes +=
# libs +=

# c_std =
# cxx_std =

.DEFAULT: all

# Run test runner on "test" target
test:
	exec ./$(test_runner)
