### Project-specific makefile

# project_name = program
# sources =
# language = c++

# cross_compile =
# w_flags =
# c_flags =
# cflags +=
# cxxflags +=

# language =

# defines +=
include_dirs += config
# includes +=
libs += m

# c_std =
# cxx_std =

# Disable LTO entirely for now as some ASM files fail rang checks if it is enabled
use_lto = n

.DEFAULT: all

include Makefile.obdh
