build_name = obdh

link_script ?= config/linker.ld

mach_flags = -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -fsingle-precision-constant -finline-functions -Wdouble-promotion

include Makefile.freertos
include Makefile.stm32f4
